### ISSUE TITLE
FreeBSD not supported (vendor/github.com/hanwen/go-fuse/v2/fuse/types.go:557:2: undefined: Attr)?

### ISSUE THREAD

**Issue by mfechner** [hanwen/go-fuse#432]
Dear all,

I currently try to make a package for FreeBSD for gocryptfs (github.com/rfjakob/gocryptfs).
But while compiling it, I see error messages like:
```
# github.com/hanwen/go-fuse/v2/fuse
vendor/github.com/hanwen/go-fuse/v2/fuse/types.go:557:2: undefined: Attr
vendor/github.com/hanwen/go-fuse/v2/fuse/types.go:585:2: undefined: Attr
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:280:41: undefined: GetAttrIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:281:41: undefined: SetAttrIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:284:39: undefined: MknodIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:308:42: undefined: SetXAttrIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:314:40: undefined: CreateIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:316:38: undefined: ReadIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:325:39: undefined: WriteIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:334:41: undefined: ReadIn
vendor/github.com/hanwen/go-fuse/v2/fuse/api.go:334:41: too many errors
github.com/jacobsa/crypto/siv
```
Could it be, that `go-fuse` does not work on FreeBSD 13.1 amd64?

Thanks a lot for any kind of help.

**Comment by da2x** [comment]
See #366.

**Comment by mfechner** [comment]
Thanks @da2x, that matches the problem.
I look a little bit through the code but I see that the package syscall is used:
https://github.com/hanwen/go-fuse/blob/master/fuse/types.go#L9

What I understand from here:
https://go.googlesource.com/proposal/+/refs/heads/master/design/freeze-syscall.md

That syscall is frozen and replaced by golang.org/x/sys:
https://pkg.go.dev/golang.org/x/sys@v0.0.0-20220704084225-05e143d24a9e

So before we could even think about getting FreeBSD support into this module I think a migration from syscall to x/sys is required.

I'm new to go, so not everything is perfectly clear for me.

**Comment by clausecker** [comment]
FreeBSD is supported now.  This issue can be closed.
